FROM php:8.1.12-fpm-alpine as base

RUN echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
    && echo "@edgecommunity http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo /etc/apk/respositories \
    apk update && apk add --no-cache bash wget git build-base autoconf pcre-dev gcc g++ postgresql-dev freetype-dev \
    openssl-dev libjpeg-turbo-dev libpng-dev busybox-suid libzip-dev unzip icu-dev oniguruma-dev $PHPIZE_DEPS \
    && docker-php-ext-install pdo_pgsql bcmath gd sockets pcntl zip intl

ENV COMPOSER_ALLOW_SUPERUSER=1 COMPOSER_HOME=/tmp
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && composer clear-cache && rm -rf /tmp/composer-setup.php /tmp/.htaccess

RUN wget https://get.symfony.com/cli/installer -O - | bash

WORKDIR /app

CMD php-fpm


